# Generated by Django 4.2.3 on 2023-07-22 13:59

from django.db import migrations
from django.contrib.postgres.operations import BtreeGinExtension


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.RunSQL(
            sql="""CREATE INDEX word_search_idx ON "words_word" USING gin (lower(word)) WITH (fastupdate = off);""",
            reverse_sql="""DROP INDEX word_search_idx;""",
        ),
    ]