name: Production Deploy

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Executing remote deploy
        uses: appleboy/ssh-action@master
        with:
          host: 95.216.111.227
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: ./dictio/scripts/deploy.sh
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_USER: ${{ secrets.DB_USER }}
